/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KButton: typeof import('mik-ui')['Button']
    KInput: typeof import('mik-ui')['Input']
    KTable: typeof import('mik-ui')['Table']
    KTableColumn: typeof import('mik-ui')['TableColumn']
  }
}
